set CLASSPATH=C:\Users\bjconove\Desktop\toweroftime-master
javac Accessory.java
javac Armor.java
javac ArmorWeaponEquip.java
javac Character.java
javac Combat.java
javac Dungeon.java
javac DungeonRoom.java
javac Encounter.java
javac Enemy.java
javac Equipment.java
javac Game.java
Javac GameFrame.java
javac Item.java
javac LegendaryEnemy.java
javac masterItems.java
javac Pack.java
javac Player.java
javac Spell.java
javac SpellBook.java
javac StartGamePanel.java
javac StatEqItPanel.java
javac UsableItem.java
javac Weapon.java
java Game
pause